name: CI • Vitest

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm
      - run: npm ci

      # Lint (opcjonalnie twardo egzekwowane)
      - run: npm run lint:ci

      # Testy z coverage i raportami (używa skrótu z package.json)
      - run: npm run test:ci

      # Artefakty (opcjonalnie)
      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit
          path: reports/junit.xml
          if-no-files-found: warn
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Upload app build
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: |
            dist
            build
            .next/out
            .next
            .output
          if-no-files-found: warn
